### ISSUE TITLE
Totally irrelevant: ignore :)

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/owl2neo#2]
There is this project 

https://github.com/VirtualFlyBrain/neo4j2owl

which has nothing to do with what you are doing, but has a sort of similar name and is managed by people in your team @dosumis  and Huseyin. No problem, just so you don't confuse each other when talking :)

**Comment by udp** [comment]
Thanks Nico, worth knowing! I am not emotionally attached to the name of this, it's just part of one of our prototypes for OLS4.
